const express=require('express');
const {register}=require("../controllers/user")
const{login}=require("../controllers/user")
const {followUser}=require("../controllers/user")
const{logout}=require("../controllers/user")
const {updatePassword}=require("../controllers/user")
const{updateProfile}=require("../controllers/user")
const{deleteMyProfile}=require("../controllers/user")
const{getUserProfile}=require("../controllers/user")
const{myProfile}=require("../controllers/user")
const{getAllUsers}=require("../controllers/user")
const{isAuthenticated}=require("../middlewares/auth")
const router=express.Router(); 
router.route("/register").post(register)
router.route("/login").post(login)
router.route("/logout").get(logout)
router.route("/update/password").put(isAuthenticated,updatePassword)
router.route("/update/profile").put(isAuthenticated,updateProfile)
router.route("/follow/:id").get(isAuthenticated,followUser)
router.route("/delete/me").delete(isAuthenticated,deleteMyProfile)
router.route("/me").get(isAuthenticated,myProfile)
router.route("/user").get(isAuthenticated,getAllUsers)
router.route("/user/:id").get(isAuthenticated,getUserProfile)
module.exports=router